version: '3.8'

services:

  db:
    image: postgres
    container_name: inflow_pg_db
    volumes:
      - ./.temp/postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: inflow-client
      POSTGRES_PASSWORD: QwerTY
      POSTGRES_DB: inflow
    ports:
      - 5432:5432
    networks:
      - default
      - service-proxy
    networks:
      - inflow-net

  api:
    build: 
      context: ./
    container_name: inflow_api
    command: ["./scripts/wait-for-postgres.sh", "python", "src/server.py"]
    environment:
      PROD_ADDR: '0.0.0.0'
      PG_USER: inflow-client
      PG_PASS: QwerTY
      PG_DB:   inflow
      PG_PORT: 5432
      PG_HOST: inflow_pg_db
    ports:
      - 3000:3000
      - 5432
    depends_on:
      - db
    networks:
      - default
      - inflow-net

networks:
  inflow-net:
    driver: bridge
