version: '3.8'

services:
  
  api:
    build: 
      context: ./server
    ports:
      - 3000:3000
      - 5432
    depends_on:
      - db
    networks:
      - default
      - service-proxy


  db:
    image: postgres
    volumes:
      - ./temp/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=inflow-client
      - POSTGRES_PASSWORD=QwerTY
      - POSTGRES_DB=inflow
    ports:
      - 5432:5432
    networks:
      - default
      - service-proxy
    # network:
    #   - inflow_net

networks:
  service-proxy:
